sonar.projectKey=aceest-fitness
sonar.projectName=ACEest Fitness
sonar.projectVersion=4.0

sonar.sources=app.py
sonar.tests=test_app.py
sonar.python.version=3.11

sonar.host.url=http://localhost:9000

sonar.exclusions=**/__pycache__/**,**/htmlcov/**,**/.pytest_cache/**
sonar.python.coverage.reportPaths=coverage.xml